name: Build Go Binary

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker run --rm \
            -v $(pwd):/src \
            -w /src \
            -e CGO_ENABLED=0 \
            -e GOOS=linux \
            -e GOARCH=amd64 \
            golang:1.22-alpine \
            go build -ldflags="-s -w" -o personal-timeline .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: personal-timeline-linux-amd64
          path: personal-timeline
